name: Deploy

on:
  push:
    branches: [ "master", "feature/auto-deploy-gh-page" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLIC_PATH: /history-timeline/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
